---
- name: Install redis
  become: yes
  package:
    name: "{{ redis_package }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: redis

- name: Allow redis to be controlled by systemd on Debian/Ubuntu
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: supervised systemd
  notify: restart redis
  tags: redis
  when: ansible_facts.os_family == 'Debian'

- name: Change bind to be ipv4 only if needed
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: "bind 127.0.0.1"
    regexp: '^bind '
  notify: restart redis
  tags: redis
  when: (ansible_facts["all_ipv6_addresses"] | length == 0)

- name: Ensure redis service is enabled and running
  become: yes
  service:
    name: redis
    enabled: yes
    state: started
  tags: redis
