---
- name: Install redis
  become: yes
  package:
    name: "{{ redis_package }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: redis

- name: Allow redis to be controlled by systemd on Debian/Ubuntu
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: supervised systemd
  notify: restart redis
  tags: redis
  when: ansible_facts.os_family == 'Debian'

- name: Update redis bind (includes ipv6 only if host has ipv6 addresses)
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: "bind {{ redis_bind_ipv4 }}{% if ansible_facts["all_ipv6_addresses"] | length > 0 %} {{ redis_bind_ipv6}}{% endif %}"
    regexp: '^bind '
  notify: restart redis
  tags: redis

- name: Update redis protected-mode
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: "protected-mode {% if redis_protected_mode %}yes{% else %}no{% endif %}"
    regexp: '^protected-mode '
  notify: restart redis
  tags: redis

- name: Update redis password for AUTH access
  become: yes
  lineinfile:
    dest: "{{ redis_conf_path }}"
    line: "requirepass {{ redis_auth_password }}"
    regexp: '^requirepass '
  notify: restart redis
  tags: redis
  when: redis_auth_password | length > 0

- name: Ensure redis service is enabled and running
  become: yes
  service:
    name: redis
    enabled: yes
    state: started
  tags: redis
