---
- name: Prepare machine for hosting MongoDB
  include_role:
    name: community.mongodb.mongodb_linux
    apply:
      tags: [databases, mongodb]
      become: yes
  tags: [databases, mongodb]

- name: Install MongoDB Repository
  include_role:
    name: community.mongodb.mongodb_repository
    apply:
      tags: [databases, mongodb]
      become: yes
  vars:
     mongodb_version: "{{ mongodb_major_minor_version }}"
  tags: [databases, mongodb]

- name: Install mongodb-org
  include_role:
    name: community.mongodb.mongodb_install
    apply:
      tags: [databases, mongodb]
      become: yes
  vars:
     specific_mongodb_version: "{{ mongodb_version }}*"
     mongodb_version: "{{ mongodb_major_minor_version }}"
  tags: [databases, mongodb]

- name: Configure and Start mongod
  include_role:
    name: community.mongodb.mongodb_mongod
    apply:
      tags: [databases, mongodb]
      become: yes
  vars:
    # assume all in one by default
    bind_ip: "{{ mongodb_bind_ip | default('127.0.0.1') }}"
    mongod_port: "{{ mongodb_port | default(27017) }}"
    replicaset: "{{ mongodb_replicaset | default(false) }}"
    repl_set_name: "{{ mongodb_replicaset_name | default('st2') }}"
    sharding: "{{ mongodb_sharding | default(false) }}"
    authorization: "{{ mongodb_authorization | default('enabled') }}"
  tags: [databases, mongodb]

- name: Install python stuff
  become: yes
  package:
    name: "python{% if needs_3 %}3{% endif %}-pip"
  vars:
    needs_3: "{{ ansible_facts.python.version.major == 3 }}"
  tags: [databases, mongodb, pip]

- name: Install pymongo (for the mongodb_user module)
  # Use pip because system packages are too old for adequate mongodb support.
  # https://docs.mongodb.com/drivers/pymongo#mongodb-compatibility
  become: yes
  pip:
    name: "pymongo>=3.10.1,<4.0.0"
  tags: [databases, mongodb]

- name: Configure mongod authentication and add users
  include_role:
    name: community.mongodb.mongodb_auth
    apply:
      tags: [databases, mongodb]
      become: yes
  tags: [databases, mongodb]
