---
- name: Check if EPEL is installed
  stat:
    path: "{{ epel_repo_file }}"
  register: epel_installed
  when: ansible_facts.os_family == "RedHat"
  tags: epel

- name: Install GPG key
  become: yes
  rpm_key:
    key: "{{ rpm_key_key }}"
    state: present
  when: ansible_facts.os_family == "RedHat" and not epel_installed.stat.exists
  tags: epel

- name: Install EPEL repo
  become: yes
  yum:
    name: "{{ epel_rpm }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  when: ansible_facts.os_family == "RedHat" and not epel_installed.stat.exists
  tags: epel
