---
- name: RabbitMQ on RHEL8 requires module(perl:5.26)
  become: yes
  shell:
     cmd: yum -y module enable perl:5.26
  #args:
  #   warn: False
  when: rabbitmq_on_el8
  register: perl_result
  changed_when:
     - '"Nothing to do" not in perl_result.stdout'
  # Disable warning as yum doesn't support enable module
  tags: [rabbitmq, skip_ansible_lint]

# TODO: if ancient EPEL7-provided rabbitmq-server or erlang-erts are installed, we need to remove them first.

- name: Install rabbitmq/erlang rpm signing gpg keys for RHEL
  become: yes
  rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - "https://packagecloud.io/rabbitmq/erlang/gpgkey"
    - "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"
  when: ansible_facts.os_family == 'RedHat'
  tags: rabbitmq

- name: Install rabbitmq/erlang from packagecloud for RHEL
  become: yes
  yum_repository:
    name: rabbitmq_erlang
    description: rabbitmq_erlang
    baseurl: https://packagecloud.io/rabbitmq/erlang/el/{{ ansible_facts.distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgkey: |-
      https://packagecloud.io/rabbitmq/erlang/gpgkey
      https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: "300"
    gpgcheck: yes
    enabled: yes
    sslverify: yes
  when: ansible_facts.os_family == 'RedHat'
  tags: rabbitmq

- name: Install latest rabbitmq erlang package on RHEL
  become: yes
  package:
    name: erlang
    state: present
  register: _eltask
  retries: 5
  delay: 3
  until: _eltask is succeeded
  when: ansible_facts.os_family == 'RedHat'
  tags: rabbitmq

- name: Install rabbit from packagecloud for RHEL
  become: yes
  yum_repository:
    name: rabbitmq_server
    description: rabbitmq_server
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/{{ ansible_facts.distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgkey: |-
      https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
      https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: "300"
    gpgcheck: yes
    enabled: yes
    sslverify: yes
  when: ansible_facts.os_family == 'RedHat'
  tags: rabbitmq

- name: Install latest rabbitmq package on {{ ansible_facts.distribution }}
  become: yes
  package:
    name: rabbitmq-server
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  notify:
    - restart rabbitmq
  tags: rabbitmq
  when: rabbitmq_version == "present"

- name: Install pinned rabbitmq package on {{ ansible_facts.distribution }}
  become: yes
  package:
    name: "rabbitmq-server{{ '=' if ansible_facts.pkg_mgr == 'apt' else '-' }}{{ rabbitmq_version }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  notify:
    - restart rabbitmq
  tags: rabbitmq
  when: rabbitmq_version != "present"

- name: Ensure rabbitmq is enabled and running
  become: yes
  service:
    name: rabbitmq-server
    enabled: yes
    state: started
  tags: rabbitmq

- name: Add RabbitMQ plugins
  become: yes
  # This does not work with rabbitmq 3.3.5 (in EPEL7). It uses a feature in 3.4.0+
  community.rabbitmq.rabbitmq_plugin:
    names: "{{ rabbitmq_plugins|join(',') }}"
    state: enabled
    # new_only: no = Remove all plguins that aren't listed in rabbitmq_plugins
    new_only: no
  when: rabbitmq_plugins | length > 0
  tags: rabbitmq

- name: Add/Remove RabbitMQ vhosts
  when: rabbitmq_vhosts or rabbitmq_absent_vhosts
  include_tasks: rabbitmq_vhosts.yml

- name: Add/Remove RabbitMQ users
  when: rabbitmq_users or rabbitmq_absent_users
  include_tasks: rabbitmq_users.yml
