---
- name: Make sure rabbitmq user options are specified correctly
  assert:
    that: (rabbitmq_keep_guest_user and 'guest' not in rabbitmq_absent_users) or rabbitmq_users|length > 0
    msg: "If the guest user is deleted, at least one other user needs to be added."
  tags: rabbitmq

- name: Remove the guest user from RabbitMQ
  become: yes
  rabbitmq_user:
    user: guest
    state: absent
  when: not rabbitmq_keep_guest_user
  tags: rabbitmq

- name: Remove other users from RabbitMQ
  become: yes
  rabbitmq_user:
    user: "{{ _rmq_user }}"
    state: absent
  loop: "{{ rabbitmq_absent_users }}"
  tags: rabbitmq

- name: Add RabbitMQ Users
  become: yes
  include_tasks: rabbitmq_user.yml
  loop_control:
    loop_var: _rmq_user
  loop: "{{ rabbitmq_users }}"
  # using loop_control: label does not obscure the password in output for verbosity > 1
  # So, loop over an include where the task name will include the user name, but the loop var won't print out.
  no_log: yes
  tags: rabbitmq
