---
# MongoDB default version (should only be x.y not x.y.z)
mongodb_version: "{% if ansible_facts.os_family == 'Debian' and ansible_facts.distribution_major_version == '20' %}4.4{% else %}4.0{% endif %}"

# pinned MongoDB version (can use x.y.z like 4.0.25)
specific_mongodb_version: "{{ mongodb_version }}*"
