---
redis_conf_path: "{{ '/etc/redis.conf' if ansible_facts.os_family == 'RedHat' else '/etc/redis/redis.conf' }}"

# By default, assume that we are doing a standalone install on the same host as st2.
# Set to false if redis and st2 are on different hosts.
redis_localhost_only: true

# override these to restrict which IPs will be bound
redis_bind_ipv4: "{% if redis_localhost_only %}127.0.0.1{% else %}0.0.0.0{% endif %}"
redis_bind_ipv6: "::{% if redis_localhost_only %}1{% endif %}"

# redis protected mode protects your redis cluster by refusing to serve requests
# to anything but localhost. If you disable this, make sure to firewall your redis host(s).
redis_protected_mode: true

# basic redis AUTH password (this not ACLs from redis 6+)
# This is how you can set this based on your st2_config:
# redis_auth_password: "{{ st2_config.coordination.url | urlsplit('password') }}"
redis_auth_password: ""
