---
- name: Install StackStorm (st2)
  hosts: "{{ st2_hosts | default('all') }}"
  environment: "{{ st2_proxy_env | default({}) }}"
  collections:
    - cognifloyd.st2_installer
    - community.mongodb
    - community.rabbitmq

  pre_tasks:
    - name: Make sure st2_config auth variables are configured
      assert:
        that:
          - st2_config is defined
          # mongodb config
          - '"database" in st2_config and "username" in st2_config.database and "password" in st2_config.database'
          # rabbitmq config
          - '"messaging" in st2_config and "url" in st2_config.messaging and (st2_config.messaging.url | urlsplit("hostname") in ["127.0.0.1", "localhost"])'
        fail_msg: |
          Cannot continue! st2_config must be configured with 
          auth credentials for mongodb and rabbitmq.
          Generally this should be added (pre-generated) to the inventory.
        success_msg: "Proceeding. st2_config is configured correctly."

    - name: Configure mongodb_users if needed
      when: mongodb_users is not defined
      set_fact:
        mongodb_users:
          - db: "{{ st2_config.database.db_name | default('st2') }}"
            user: "{{ st2_config.database.username }}"
            pwd: "{{ st2_config.database.password }}"
            roles: readWrite,dbAdmin

    - name: Configure rabbitmq_users if needed
      when: rabbitmq_users is not defined
      set_fact:
        rabbitmq_users:
          - user: '{{ st2_config.messaging.url | urlsplit("username") }}'
            password: '{{ st2_config.messaging.url | urlsplit("password") }}'
            permissions:
              - vhost: '{{ (st2_config.messaging.url | urlsplit("path"))[1:] | default("/", true) }}'
                configure_priv: .*
                read_priv: .*
                write_priv: .*

  vars:
    mongodb_bind_ip: '{{ st2_config.database.host | default("127.0.0.1") }}'
    mongodb_port: '{{ st2_config.database.port | default("27017") }}'
    mongodb_replicaset: false
    mongodb_sharding: false
    mongodb_authorization: "enabled"
    # Should set mongodb_admin_pwd in inventory
    mongodb_default_admin_pwd: "{{ st2_config.database.password }}"

  roles:
    - name: Mongo | Main DB for StackStorm
      role: mongodb

    - name: RabbitMQ | Message Broker for StackStorm
      role: rabbitmq

    - name: EPEL | Add EPEL repo to RHEL/CentOS
      role: epel
      when: ansible_facts.os_family == 'RedHat'

    - name: ST2 | Add StackStorm PackageCloud repositories
      role: st2repo

    - name: ST2 | Install and configure StackStorm (st2)
      role: st2

    - name: Nginx | Access point for st2web
      role: nginx

    - name: ST2 | Install st2web
      role: st2web

    - name: Node.js | Install node.js for st2chatops
      role: nodejs

    - name: ST2 | Install st2chatops and a hubot adapter
      role: st2chatops

    - name: ST2 | Verify StackStorm installation
      role: st2smoketests
