# based on example from:
# https://github.com/marketplace/actions/ansible-lint
# https://github.com/ansible/ansible-lint-action
---
name: Push/Merge - Ansible Lint

on:
  push:
    branches-ignore:
      - 'ansible-st2-*'

jobs:
  lint:

    runs-on: ubuntu-latest
    container: 
      image: yokogawa/ansible-lint:v4.3.7
#      volumes:
#        - ~/.ansible/collections:~/.ansible/collections
      options: '-v "/home/runner/.ansible/collections":"/github/home/.ansible/collections"'

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbooks/Roles
        run: 'sh -c "ansible-lint -v --force-color playbooks/*.playbook.yml roles/*/"'

      # I would prefer to use an ansible action, but it always rebuilds docker image.
      # - name: Lint Ansible Playbooks/Roles
      #  # use master (no recent tags: https://github.com/ansible/ansible-lint-action/issues/23 )
      #  uses: ansible/ansible-lint-action@master
      #  with:
      #    # [required]
      #    # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
      #    # or valid Ansible directories according to the Ansible role
      #    # directory structure.
      #    targets: |
      #      playbooks/*.playbook.yml
      #      roles/*/
      #    # [optional]
      #    # Arguments to override a package and its version to be set explicitly.
      #    override-deps: |
      #      ansible~=2.10.3
      #      ansible-lint~=4.3.7
      #    # [optional]
      #    # Arguments to be passed to the ansible-lint
      #    # https://ansible-lint.readthedocs.io/en/latest/usage.html#command-line-options
      #    args: ""

      - name: Restore Collections Cache
        id: cache
        # uses: actions/cache@v2
        uses: ylemkimon/cache-restore@v2
        with:
          path: |
            /home/runner/.ansible/collections/ansible_collections/
            !/home/runner/.ansible/collections/ansible_collections/*/st2_installer/
          key: deps-collections-${{ hashFiles('requirements.yml') }}-${{ hashFiles('galaxy.yml') }}
          restore-keys: |
            deps-collections-${{ hashFiles('requirements.yml') }}-
            deps-collections-

      - name: Install Collection Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ansible-galaxy collection install -r requirements.yml

      - name: Build st2_installer Collection
        run: ansible-galaxy collection build

      - name: Install st2_installer Collection
        run: 'sh -c "ansible-galaxy collection install *-st2_installer-*.tar.gz"'

      - name: Check Ansible Playbook Syntax
        run: 'sh -c "ansible-playbook -vvv --syntax-check -e st2_hosts=localhost playbooks/*.playbook.yml"'
