# based on example from:
# https://github.com/marketplace/actions/ansible-lint
# https://github.com/ansible/ansible-lint-action
---
name: Push/Merge - Ansible Lint

on:
  push:
    branches-ignore:
      - 'ansible-st2-*'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbooks/Roles
        uses: docker://yokogawa/ansible-lint:v4.3.7
        with:
          entrypoint: sh
          # upstream does '-x 106,204,208'
          args: '-c "ansible-lint -v --force-color playbooks/*.playbook.yml roles/*/"'

      # I would prefer to use an ansible action, but it always rebuilds docker image.
      # - name: Lint Ansible Playbooks/Roles
      #  # use master (no recent tags: https://github.com/ansible/ansible-lint-action/issues/23 )
      #  uses: ansible/ansible-lint-action@master
      #  with:
      #    # [required]
      #    # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
      #    # or valid Ansible directories according to the Ansible role
      #    # directory structure.
      #    targets: |
      #      playbooks/*.playbook.yml
      #      roles/*/
      #    # [optional]
      #    # Arguments to override a package and its version to be set explicitly.
      #    override-deps: |
      #      ansible~=2.10.3
      #      ansible-lint~=4.3.7
      #    # [optional]
      #    # Arguments to be passed to the ansible-lint
      #    # https://ansible-lint.readthedocs.io/en/latest/usage.html#command-line-options
      #    args: ""

      - name: Install collections
        uses: docker://yokogawa/ansible-lint:v4.3.7
        with:
          entrypoint: ansible-galaxy
          args: collection install -r requirements.yml

      - name: Build this collection
        uses: docker://yokogawa/ansible-lint:v4.3.7
        with:
          entrypoint: ansible-galaxy
          args: collection build

      - name: Install this collection
        uses: docker://yokogawa/ansible-lint:v4.3.7
        with:
          entrypoint: sh
          args: '-c "ansible-galaxy collection install *-st2_installer-*.tar.gz"'

      - name: Check Ansible Playbook Syntax
        uses: docker://yokogawa/ansible-lint:v4.3.7
        with:
          entrypoint: sh
          args: '-c "ansible-playbook -v --syntax-check playbooks/*.playbook.yml"'
