---
name: track-ansible-st2
on:
  schedule:
    - cron: '0 8 * * *' # UTC
  workflow_dispatch:
    # TODO: find a way to do an input for git_sync_command and git_push_args
    # while providing a default value for the cron job (maybe one sync step if cron, and one if workflow_dispatch)

    # inputs:
    #  git_sync_command:
    #    description: 'Whether to sync with a "merge --ff-only" (default) or a "reset --hard"'
    #    required: false
    #    # TODO: choices: only "merge --ff-only" or "reset --hard"
    #    default: 'merge --ff-only'
    #  git_push_args:
    #    description: 'Add "--force" arg when pushing after doing a "reset --hard" sync'
    #    required: false
    #    # TODO: choices: only "" or "--force"
    #    default: ''

jobs:
  track-and-merge-from-ansible-st2:
    runs-on: ubuntu-latest
    name: Update tracking and merge branches from StackStorm/ansible-st2:master
    steps:
      - name: Checkout ansible-st2-tracking
        uses: actions/checkout@v2
        with:
          ref: ansible-st2-tracking

      - name: Sync changes from StackStorm/ansible-st2
        id: sync
        # uses: aormsby/Fork-Sync-With-Upstream-action@v2.0
        uses: cognifloyd/Fork-Sync-With-Upstream-action@fix-sync-command
        with:
          upstream_repository: StackStorm/ansible-st2
          upstream_branch: master
          target_branch: ansible-st2-tracking
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # git_sync_command: pull --ff-only
          git_sync_command: merge --ff-only  # oops. action has a bug if it is not pull.
          # git_sync_command: ${{ github.event.inputs.git_sync_command }}
          # git_push_args: ${{ github.event.inputs.git_push_args }}

      - name: Merge ansible-st2-tracking and ansible-st2-staging branches
        if: ${{ steps.sync.outputs.has_new_commits == 'true' }}
        # staging has very basic modifications to simplify the later merge
        uses: tukasz/direct-merge-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ansible-st2-tracking
          target-branch: ansible-st2-staging

      - name: Create PR from ansible-st2-staging to ansible-st2-merge for manual review
        id: pr
        if: ${{ steps.sync.outputs.has_new_commits == 'true' }}
        # uses: sudoStatus200/create-sync-pr@0.3.1
        uses: cognifloyd/create-sync-pr@use-source-branch
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_BRANCH: ansible-st2-staging
          TARGET_BRANCH: ansible-st2-merge
      # TODO on create PR failure,
      #   revert ansible-st2-tracking to steps.sync.outputs.old_sha
      #   revert ansible-st2-staging to ??? (direct-merge-action needs old/new sha output vars)

      - name: Merge ansible-st2-merge into PR branch
        if: ${{ steps.sync.outputs.has_new_commits == 'true' }}
        uses: tukasz/direct-merge-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ansible-st2-merge
          target-branch: ${{ steps.pr.outputs.PULL_REQUEST_BRANCH }}
